export const allVideoTestimonials = [
  {
    id: 1,
    name: "Kulveer",
    profession: "Financial Analyst",
    country: "Germany",
    flag: "",
    duration: "Success Story",
    thumbnail: "https://img.youtube.com/vi/4zqYn_0y78A/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/watch?v=4zqYn_0y78A",
    achievement: "Moved Abroad Successfully",
    quote: "From India to Germany as Financial Analyst",
    details: "How Kulveer Moved Abroad as a Financial Analyst | Real Story by Indians_Abroad"
  },
  {
    id: 2,
    name: "Yogita",
    profession: "Immigration Success",
    country: "Germany",
    flag: "",
    duration: "Opportunity Card",
    thumbnail: "https://img.youtube.com/vi/IvGYk6owjUk/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/watch?v=IvGYk6owjUk",
    achievement: "Opportunity Card Success",
    quote: "Inspiring journey to Germany",
    details: "Yogita's Inspiring Abroad Journey | Indians_Abroad Success Story | Opportunity Card"
  },
  {
    id: 3,
    name: "Rohit",
    profession: "Business Systems Specialist",
    country: "Abroad",
    flag: "",
    duration: "Success Story",
    thumbnail: "https://img.youtube.com/vi/3zlQbkcYmOA/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/watch?v=3zlQbkcYmOA",
    achievement: "Business Systems Specialist Success",
    quote: "Real abroad journey transformation",
    details: "Rohit's Real Abroad Journey | Business Systems Specialist Success Story | Indians_Abroad"
  },
  {
    id: 4,
    name: "Success Story",
    profession: "Professional Journey",
    country: "International",
    flag: "",
    duration: "Career Success",
    thumbnail: "https://img.youtube.com/vi/BGp2eZSJlvM/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/watch?v=BGp2eZSJlvM",
    achievement: "International Career Success",
    quote: "Transforming dreams into reality",
    details: "Inspiring journey of professional growth and international success"
  },
  {
    id: 5,
    name: "Career Achievement",
    profession: "Global Professional",
    country: "Worldwide",
    flag: "",
    duration: "Success Journey",
    thumbnail: "https://img.youtube.com/vi/MGPr0DcznmU/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/watch?v=MGPr0DcznmU",
    achievement: "Global Career Advancement",
    quote: "Building a successful international career",
    details: "From local opportunities to global success - a transformation story"
  },
  {
    id: 6,
    name: "Immigration Success",
    profession: "Skilled Professional",
    country: "Multiple Destinations",
    flag: "",
    duration: "Journey Story",
    thumbnail: "https://img.youtube.com/vi/DN42js9AcLg/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/watch?v=DN42js9AcLg",
    achievement: "Successful Immigration Journey",
    quote: "Making the dream of living abroad a reality",
    details: "Complete guide to successful immigration and settlement abroad"
  },
  {
    id: 7,
    name: "Work Visa Success",
    profession: "Visa Specialist",
    country: "Global",
    flag: "",
    duration: "Visa Process",
    thumbnail: "https://img.youtube.com/vi/pVeNuBWEQQs/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/watch?v=pVeNuBWEQQs",
    achievement: "Work Visa Approval",
    quote: "Work visa process made simple",
    details: "Complete work visa application and approval process"
  },
  {
    id: 8,
    name: "Client Success Story",
    profession: "Immigration Success",
    country: "Abroad",
    flag: "",
    duration: "Journey Documentary",
    thumbnail: "https://img.youtube.com/vi/e-tzXobhKoI/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/watch?v=e-tzXobhKoI",
    achievement: "Successful Immigration",
    quote: "Another inspiring success story",
    details: "Complete journey documentation and success story"
  },
  {
    id: 9,
    name: "Professional Success",
    profession: "Career Transformation",
    country: "International",
    flag: "",
    duration: "Career Change",
    thumbnail: "https://img.youtube.com/vi/BVKvCYnL7i4/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/watch?v=BVKvCYnL7i4",
    achievement: "Career Transformation",
    quote: "From local to international career",
    details: "Professional transformation and career success abroad"
  },
  {
    id: 10,
    name: "Immigration Journey",
    profession: "Settlement Success",
    country: "Multiple Countries",
    flag: "",
    duration: "Settlement Guide",
    thumbnail: "https://img.youtube.com/vi/F6WTQ6Wn9dI/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/watch?v=F6WTQ6Wn9dI",
    achievement: "Successful Settlement",
    quote: "Complete settlement guidance",
    details: "Step-by-step settlement process and success tips"
  },
  {
    id: 11,
    name: "Parwinder",
    profession: "Opportunity Card Holder",
    country: "Germany",
    flag: "🇩🇪",
    duration: "Opportunity Card",
    thumbnail: "https://img.youtube.com/vi/V0YdlCuSIvo/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/watch?v=V0YdlCuSIvo",
    achievement: "Germany Opportunity Card Success",
    quote: "How I moved from India to Germany",
    details: "Germany Opportunity Card Success Story | How Parwinder Moved from India"
  },
  {
    id: 12,
    name: "Shriharsha",
    profession: "IT Professional",
    country: "Germany",
    flag: "🇩🇪",
    duration: "Opportunity Card",
    thumbnail: "https://img.youtube.com/vi/fhYmwaBIfIk/hqdefault.jpg",
    videoUrl: "https://www.youtube.com/watch?v=fhYmwaBIfIk",
    achievement: "Germany Opportunity Card Approved",
    quote: "IT professional's path to Germany",
    details: "How Shriharsha (IT professional) Got Germany Opportunity Card | Real Indian Success Story"
  },
  {
    id: 13,
    name: "Abir",
    profession: "Opportunity Card Applicant",
    country: "Germany",
    flag: "🇩🇪",
    duration: "Full Process",
    thumbnail: "https://img.youtube.com/vi/fD0EwHG76jg/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/watch?v=fD0EwHG76jg",
    achievement: "Germany Opportunity Card Process",
    quote: "Complete opportunity card journey",
    details: "Germany Opportunity Card 2025 | Full Process for Indian for Abir"
  },
  {
    id: 14,
    name: "Palak",
    profession: "Opportunity Card Applicant",
    country: "Germany",
    flag: "🇩🇪",
    duration: "Full Process",
    thumbnail: "https://img.youtube.com/vi/mp3yrmJrxBQ/hqdefault.jpg",
    videoUrl: "https://www.youtube.com/watch?v=mp3yrmJrxBQ",
    achievement: "Germany Opportunity Card Process",
    quote: "Step-by-step opportunity card guide",
    details: "Germany Opportunity Card 2025 | Full Process for Indian for Palak"
  }
];
